
package services.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeePort", targetNamespace = "http://employee.services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeePort {


    /**
     * 
     * @param displayAllRequest
     * @return
     *     returns services.employee.DisplayAllResponse
     */
    @WebMethod
    @WebResult(name = "displayAllResponse", targetNamespace = "http://employee.services", partName = "displayAllResponse")
    public DisplayAllResponse displayAll(
        @WebParam(name = "displayAllRequest", targetNamespace = "http://employee.services", partName = "displayAllRequest")
        DisplayAllRequest displayAllRequest);

    /**
     * 
     * @param displayBasedOnPincodeRequest
     * @return
     *     returns services.employee.DisplayBasedOnPincodeResponse
     */
    @WebMethod
    @WebResult(name = "displayBasedOnPincodeResponse", targetNamespace = "http://employee.services", partName = "displayBasedOnPincodeResponse")
    public DisplayBasedOnPincodeResponse displayBasedOnPincode(
        @WebParam(name = "displayBasedOnPincodeRequest", targetNamespace = "http://employee.services", partName = "displayBasedOnPincodeRequest")
        DisplayBasedOnPincodeRequest displayBasedOnPincodeRequest);

    /**
     * 
     * @param newEmployeeRequest
     * @return
     *     returns services.employee.NewEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "newEmployeeResponse", targetNamespace = "http://employee.services", partName = "newEmployeeResponse")
    public NewEmployeeResponse newEmployee(
        @WebParam(name = "newEmployeeRequest", targetNamespace = "http://employee.services", partName = "newEmployeeRequest")
        NewEmployeeRequest newEmployeeRequest);

    /**
     * 
     * @param displayBasedOnIdRequest
     * @return
     *     returns services.employee.DisplayBasedOnIdResponse
     */
    @WebMethod
    @WebResult(name = "displayBasedOnIdResponse", targetNamespace = "http://employee.services", partName = "displayBasedOnIdResponse")
    public DisplayBasedOnIdResponse displayBasedOnId(
        @WebParam(name = "displayBasedOnIdRequest", targetNamespace = "http://employee.services", partName = "displayBasedOnIdRequest")
        DisplayBasedOnIdRequest displayBasedOnIdRequest);

    /**
     * 
     * @param employeeExistsRequest
     * @return
     *     returns services.employee.EmployeeExistsResponse
     */
    @WebMethod
    @WebResult(name = "employeeExistsResponse", targetNamespace = "http://employee.services", partName = "employeeExistsResponse")
    public EmployeeExistsResponse employeeExists(
        @WebParam(name = "employeeExistsRequest", targetNamespace = "http://employee.services", partName = "employeeExistsRequest")
        EmployeeExistsRequest employeeExistsRequest);

}
