//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.12 at 05:04:18 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://payee.services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package services.payee;
