//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.08 at 10:17:59 PM IST 
//


package services.employee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employeeBasic" type="{http://employee.services}employebasicdetails"/>
 *         &lt;element name="temporaryEmployeeAddress" type="{http://employee.services}employeeaddress"/>
 *         &lt;element name="permanentEmployeeAddress" type="{http://employee.services}employeeaddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "employeeBasic",
    "temporaryEmployeeAddress",
    "permanentEmployeeAddress"
})
@XmlRootElement(name = "newEmployeeRequest")
public class NewEmployeeRequest {

    @XmlElement(required = true)
    protected Employebasicdetails employeeBasic;
    @XmlElement(required = true)
    protected Employeeaddress temporaryEmployeeAddress;
    @XmlElement(required = true)
    protected Employeeaddress permanentEmployeeAddress;

    /**
     * Gets the value of the employeeBasic property.
     * 
     * @return
     *     possible object is
     *     {@link Employebasicdetails }
     *     
     */
    public Employebasicdetails getEmployeeBasic() {
        return employeeBasic;
    }

    /**
     * Sets the value of the employeeBasic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employebasicdetails }
     *     
     */
    public void setEmployeeBasic(Employebasicdetails value) {
        this.employeeBasic = value;
    }

    /**
     * Gets the value of the temporaryEmployeeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Employeeaddress }
     *     
     */
    public Employeeaddress getTemporaryEmployeeAddress() {
        return temporaryEmployeeAddress;
    }

    /**
     * Sets the value of the temporaryEmployeeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employeeaddress }
     *     
     */
    public void setTemporaryEmployeeAddress(Employeeaddress value) {
        this.temporaryEmployeeAddress = value;
    }

    /**
     * Gets the value of the permanentEmployeeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Employeeaddress }
     *     
     */
    public Employeeaddress getPermanentEmployeeAddress() {
        return permanentEmployeeAddress;
    }

    /**
     * Sets the value of the permanentEmployeeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employeeaddress }
     *     
     */
    public void setPermanentEmployeeAddress(Employeeaddress value) {
        this.permanentEmployeeAddress = value;
    }

}
