//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.08 at 10:17:59 PM IST 
//


package services.employee;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.employee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.employee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewEmployeeRequest }
     * 
     */
    public NewEmployeeRequest createNewEmployeeRequest() {
        return new NewEmployeeRequest();
    }

    /**
     * Create an instance of {@link Employebasicdetails }
     * 
     */
    public Employebasicdetails createEmployebasicdetails() {
        return new Employebasicdetails();
    }

    /**
     * Create an instance of {@link Employeeaddress }
     * 
     */
    public Employeeaddress createEmployeeaddress() {
        return new Employeeaddress();
    }

    /**
     * Create an instance of {@link NewEmployeeResponse }
     * 
     */
    public NewEmployeeResponse createNewEmployeeResponse() {
        return new NewEmployeeResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

}
