//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.12 at 05:04:18 PM IST 
//


package services.payee;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.payee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.payee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindAllPayeeBasedOnAccountNumberResponse }
     * 
     */
    public FindAllPayeeBasedOnAccountNumberResponse createFindAllPayeeBasedOnAccountNumberResponse() {
        return new FindAllPayeeBasedOnAccountNumberResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link Payee }
     * 
     */
    public Payee createPayee() {
        return new Payee();
    }

    /**
     * Create an instance of {@link FindAllPayeeBasedOnAccountNumberRequest }
     * 
     */
    public FindAllPayeeBasedOnAccountNumberRequest createFindAllPayeeBasedOnAccountNumberRequest() {
        return new FindAllPayeeBasedOnAccountNumberRequest();
    }

    /**
     * Create an instance of {@link FindAllPayeeRequest }
     * 
     */
    public FindAllPayeeRequest createFindAllPayeeRequest() {
        return new FindAllPayeeRequest();
    }

    /**
     * Create an instance of {@link FindAllPayeeReqResponse }
     * 
     */
    public FindAllPayeeReqResponse createFindAllPayeeReqResponse() {
        return new FindAllPayeeReqResponse();
    }

    /**
     * Create an instance of {@link PayeeRequired }
     * 
     */
    public PayeeRequired createPayeeRequired() {
        return new PayeeRequired();
    }

    /**
     * Create an instance of {@link FindAllPayeeResponse }
     * 
     */
    public FindAllPayeeResponse createFindAllPayeeResponse() {
        return new FindAllPayeeResponse();
    }

    /**
     * Create an instance of {@link FindAllPayeeBasedOnAccountNumberLambdaResponse }
     * 
     */
    public FindAllPayeeBasedOnAccountNumberLambdaResponse createFindAllPayeeBasedOnAccountNumberLambdaResponse() {
        return new FindAllPayeeBasedOnAccountNumberLambdaResponse();
    }

    /**
     * Create an instance of {@link FindAllPayeeReqRequest }
     * 
     */
    public FindAllPayeeReqRequest createFindAllPayeeReqRequest() {
        return new FindAllPayeeReqRequest();
    }

    /**
     * Create an instance of {@link FindAllPayeeBasedOnAccountNumberLambdaRequest }
     * 
     */
    public FindAllPayeeBasedOnAccountNumberLambdaRequest createFindAllPayeeBasedOnAccountNumberLambdaRequest() {
        return new FindAllPayeeBasedOnAccountNumberLambdaRequest();
    }

}
